In [20]:
makeMeanDataset <- function(x) {
    mean = NULL
    set <- function(y) {
        x <<- y
        mean <<- NULL
    }
    get <- function() x
    getmean <- function() mean
    setmean <- function(m) mean <<- m
    list(set=set, get=get, getmean=getmean, setmean=setmean)
}

In [21]:
cachemean <- function(x, ...) {
  m <- x$getmean()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- mean(data, ...)
  x$setmean(m)
  m
}

In [22]:
ls()

[1] "cachemean"       "cacheSolve"      "m"               "makeCacheMatrix"
[5] "makeMeanDataset" "x"

In [23]:
x = c(1, 2, 3, 4)

In [25]:
m = makeMeanDataset(x)

In [26]:
m$get()

[1] 1 2 3 4

In [27]:
cachemean(m)

[1] 2.5

In [28]:
cachemean(m)

getting cached data


[1] 2.5

----

In [3]:
# Matrix inversion is usually a costly computation and there may be some benefit
# to caching the inverse of a matrix rather than compute it repeatedly. The
# following two functions are used to cache the inverse of a matrix.

# makeCacheMatrix creates a list containing functions to
# 1. set the value of the matrix
# 2. get the value of the matrix
# 3. set the value of inverse of the matrix
# 4. get the value of inverse of the matrix
makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)
}

In [4]:
# The following function returns the inverse of the matrix. It first checks if
# the inverse has already been computed. If so, it gets the result and skips the
# computation. If not, it computes the inverse, sets the value in the cache via
# setinverse function.

# This function assumes that the matrix is always invertible.
cacheSolve <- function(x, ...) {
    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data.")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinverse(inv)
    inv
}

In [ ]:
## Sample run:
## > x = rbind(c(1, -1/4), c(-1/4, 1))
## > m = makeCacheMatrix(x)
## > m$get()
##       [,1]  [,2]
## [1,]  1.00 -0.25
## [2,] -0.25  1.00

## No cache in the first run
## > cacheSolve(m)
##           [,1]      [,2]
## [1,] 1.0666667 0.2666667
## [2,] 0.2666667 1.0666667

## Retrieving from the cache in the second run
## > cacheSolve(m)
## getting cached data.
##           [,1]      [,2]
## [1,] 1.0666667 0.2666667
## [2,] 0.2666667 1.0666667
## > 

In [5]:
x = rbind(c(1, -1/4), c(-1/4, 1)); x

[,1]  [,2]
[1,]  1.00 -0.25
[2,] -0.25  1.00

In [6]:
m = makeCacheMatrix(x)

In [8]:
m # list of 4 functions

$set
function (y) 
{
    x <<- y
    inv <<- NULL
}
<environment: 0x7fad0bcdb868>

$get
function () 
x
<environment: 0x7fad0bcdb868>

$setinverse
function (inverse) 
inv <<- inverse
<environment: 0x7fad0bcdb868>

$getinverse
function () 
inv
<environment: 0x7fad0bcdb868>

In [9]:
m$get()

[,1]  [,2]
[1,]  1.00 -0.25
[2,] -0.25  1.00

In [10]:
m$getinverse()

NULL

In [11]:
cacheSolve(m)

[,1]      [,2]
[1,] 1.0666667 0.2666667
[2,] 0.2666667 1.0666667

In [12]:
cacheSolve(m)

getting cached data.


[,1]      [,2]
[1,] 1.0666667 0.2666667
[2,] 0.2666667 1.0666667