In [2]:
x<-list(a=1:5, b=rnorm(10))

In [3]:
x

$a
[1] 1 2 3 4 5

$b
 [1]  0.1445203 -0.1014180  1.3259081  0.8594785 -0.8731815 -0.6023066
 [7] -0.3726750  0.3299843  0.8155674  1.4752880

In [4]:
lapply(x,mean)

$a
[1] 3

$b
[1] 0.3001165

In [5]:
x<-list(a=1:4, b=rnorm(10), c=rnorm(20,1), d=rnorm(100,5))
lapply(x,mean)

$a
[1] 2.5

$b
[1] -0.109522

$c
[1] 1.284404

$d
[1] 4.978562

In [6]:
x<-1:4
lapply(x,runif)

[[1]]
[1] 0.3717147

[[2]]
[1] 0.9098153 0.8185319

[[3]]
[1] 0.7746250 0.3598249 0.6639085

[[4]]
[1] 0.5500781 0.6816424 0.9416856 0.2033487

In [10]:
lapply(x,runif,min=0,max=10)

[[1]]
[1] 0.6698327

[[2]]
[1] 9.6553117 0.9595093

[[3]]
[1] 7.843951 9.910664 1.183075

[[4]]
[1] 1.386740 7.853611 9.530457 4.515502

In [ ]:
x<-list(a=matrix(1:4,2,2),b=matrix(1:6,3,2))

In [27]:
matrix(1:4,2,2); matrix(1:6,3,2)

[,1] [,2]
[1,]    1    3
[2,]    2    4

[,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [28]:
lapply(x,function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

In [30]:
x<-list(a=1:4, b=rnorm(10), c=rnorm(20,1), d=rnorm(100,5))
sapply(x,mean)

a          b          c          d 
 2.5000000 -0.1391714  1.2161126  4.9175641

In [31]:
lapply(x,mean)

$a
[1] 2.5

$b
[1] -0.1391714

$c
[1] 1.216113

$d
[1] 4.917564

In [35]:
x<-matrix(rnorm(24),4,6); x

[,1]       [,2]        [,3]       [,4]       [,5]       [,6]
[1,] 0.5910900 -0.2807897  0.34132190 -0.7700778  0.2177460  1.6132143
[2,] 1.0446470  0.3358755 -0.04372527  1.1752561  0.2358266  1.0209114
[3,] 1.0731322  2.0030573 -0.24423671 -0.5719185  1.2877557  0.8082484
[4,] 0.3969362  0.3814870 -0.68849578 -0.5345657 -0.9318929 -0.6808898

In [36]:
apply(x,2,mean)
apply(x,1,sum)

[1]  0.7764513  0.6099075 -0.1587840 -0.1753265  0.2023589  0.6903711

[1]  1.712505  3.768791  4.356038 -2.057421

In [37]:
rowSums=apply(x,1,sum); rowSums

[1]  1.712505  3.768791  4.356038 -2.057421

In [41]:
rowMeans=apply(x,1,mean); rowMeans

[1]  0.2854174  0.6281319  0.7260064 -0.3429035

In [42]:
colSums=apply(x,2,sum); colSums
colMeans=apply(x,2,mean); colMeans

[1]  3.1058053  2.4396301 -0.6351359 -0.7013059  0.8094354  2.7614844

[1]  0.7764513  0.6099075 -0.1587840 -0.1753265  0.2023589  0.6903711

In [49]:
x<-matrix(rnorm(24),4,6)
apply(x,1,quantile,probs=c(0.25,0.75))

[,1]       [,2]       [,3]       [,4]
25% -0.2368548 -0.3701728 -0.4968777 -0.6013212
75%  0.4215496  1.0109324  0.9051107  0.4843653

In [51]:
class(apply(x,1,quantile,probs=c(0.25,0.75))); dim(apply(x,1,quantile,probs=c(0.25,0.75)))

[1] "matrix"

[1] 2 4

In [55]:
a<-array(rnorm(2*2*10),c(2,2,10)); a

, , 1

          [,1]       [,2]
[1,]  1.207201 -0.7653633
[2,] -1.230041  0.3543063

, , 2

           [,1]       [,2]
[1,] -0.9369313  0.6129784
[2,]  0.0962378 -0.9812464

, , 3

           [,1]      [,2]
[1,]  0.5638460 0.5301416
[2,] -0.1106941 0.8003799

, , 4

           [,1]      [,2]
[1,] -1.1396419 0.9358919
[2,] -0.9079086 0.3853580

, , 5

          [,1]       [,2]
[1,]  1.769665 -0.2568735
[2,] -1.062220  0.5501829

, , 6

            [,1]       [,2]
[1,]  0.99654572 -0.4170739
[2,] -0.08427851  0.9035125

, , 7

           [,1]        [,2]
[1,] -0.4047961 -0.02895188
[2,] -2.0508846  0.98978094

, , 8

            [,1]      [,2]
[1,]  0.85059931 0.8310112
[2,] -0.05027858 1.0541907

, , 9

           [,1]       [,2]
[1,] -1.0192360  0.1964289
[2,]  0.3038169 -0.9904594

, , 10

         [,1]      [,2]
[1,] 0.663214 0.2598414
[2,] 2.518367 0.5837202

Think of this as a cuboid with dimension as 2 x 2 x 10

In [58]:
apply(a,c(1,2),mean)

[,1]      [,2]
[1,]  0.2550466 0.1898031
[2,] -0.2577884 0.3649726

In [59]:
rowMeans(a,dims=2)

[,1]      [,2]
[1,]  0.2550466 0.1898031
[2,] -0.2577884 0.3649726

In [63]:
x <- c(rnorm(10),runif(10),rnorm(10,1)); x

[1]  0.652743277 -0.786187606 -0.687042726 -3.400754454  1.195189635
 [6] -0.909910782 -1.271163537  0.008421132  0.051359681 -0.620850871
[11]  0.571434977  0.637851011  0.832606025  0.265487815  0.998083354
[16]  0.916219729  0.507695863  0.065230617  0.743955468  0.289455961
[21] -0.221653767  0.519041024  0.448308628  1.012782333  0.457461869
[26]  0.967503887  0.913108119  1.583782041  2.648709593  1.770327920

In [67]:
f<-gl(3,10); f  # Generate factor levels

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

In [68]:
tapply(x,f,mean)

1          2          3 
-0.5768196  0.5828021  1.0099372

In [69]:
tapply(x,f,mean,simplify=FALSE)

$`1`
[1] -0.5768196

$`2`
[1] 0.5828021

$`3`
[1] 1.009937

In [70]:
tapply(x,f,range)

$`1`
[1] -3.400754  1.195190

$`2`
[1] 0.06523062 0.99808335

$`3`
[1] -0.2216538  2.6487096

In [71]:
split(x,f)

$`1`
 [1]  0.652743277 -0.786187606 -0.687042726 -3.400754454  1.195189635
 [6] -0.909910782 -1.271163537  0.008421132  0.051359681 -0.620850871

$`2`
 [1] 0.57143498 0.63785101 0.83260602 0.26548782 0.99808335 0.91621973
 [7] 0.50769586 0.06523062 0.74395547 0.28945596

$`3`
 [1] -0.2216538  0.5190410  0.4483086  1.0127823  0.4574619  0.9675039
 [7]  0.9131081  1.5837820  2.6487096  1.7703279

In [72]:
lapply(split(x,f),mean)

$`1`
[1] -0.5768196

$`2`
[1] 0.5828021

$`3`
[1] 1.009937

In [73]:
library(datasets)
head(airquality)

Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6

In [76]:
unique(airquality$Month)

[1] 5 6 7 8 9

In [77]:
s<-split(airquality,airquality$Month)

In [80]:
head(s$"6")

Ozone Solar.R Wind Temp Month Day
32    NA     286  8.6   78     6   1
33    NA     287  9.7   74     6   2
34    NA     242 16.1   67     6   3
35    NA     186  9.2   84     6   4
36    NA     220  8.6   85     6   5
37    NA     264 14.3   79     6   6

In [81]:
lapply(s,function(x) colMeans(x[,c("Ozone","Solar.R","Wind")]))

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [82]:
sapply(s,function(x) colMeans(x[,c("Ozone","Solar.R","Wind")]))

5         6          7        8        9
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

In [83]:
sapply(s,function(x) colMeans(x[,c("Ozone","Solar.R","Wind")],na.rm=TRUE))

5         6          7          8         9
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

----

In [89]:
x<-rnorm(10);x
f1<-gl(2,5);f1
f2<-gl(5,2);f2

[1] -1.22572803  0.18296282  1.54989365  2.49712431 -0.33700496  0.89264320
 [7] -1.97863557  0.27359585  1.45663992  0.04630115

[1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

[1] 1 1 2 2 3 3 4 4 5 5
Levels: 1 2 3 4 5

In [90]:
interaction(f1,f2) #Creates a factor which represent interaction of given factors.

[1] 1.1 1.1 1.2 1.2 1.3 2.3 2.4 2.4 2.5 2.5
Levels: 1.1 2.1 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5

In [92]:
list(f1, f2)

[[1]]
 [1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

[[2]]
 [1] 1 1 2 2 3 3 4 4 5 5
Levels: 1 2 3 4 5

In [94]:
split(x,list(f1,f2))

$`1.1`
[1] -1.2257280  0.1829628

$`2.1`
numeric(0)

$`1.2`
[1] 1.549894 2.497124

$`2.2`
numeric(0)

$`1.3`
[1] -0.337005

$`2.3`
[1] 0.8926432

$`1.4`
numeric(0)

$`2.4`
[1] -1.9786356  0.2735958

$`1.5`
numeric(0)

$`2.5`
[1] 1.45663992 0.04630115

In [93]:
str(split(x,list(f1,f2)))

List of 10
 $ 1.1: num [1:2] -1.226 0.183
 $ 2.1: num(0) 
 $ 1.2: num [1:2] 1.55 2.5
 $ 2.2: num(0) 
 $ 1.3: num -0.337
 $ 2.3: num 0.893
 $ 1.4: num(0) 
 $ 2.4: num [1:2] -1.979 0.274
 $ 1.5: num(0) 
 $ 2.5: num [1:2] 1.4566 0.0463


In [95]:
split(x,list(f1,f2),drop=TRUE)

$`1.1`
[1] -1.2257280  0.1829628

$`1.2`
[1] 1.549894 2.497124

$`1.3`
[1] -0.337005

$`2.3`
[1] 0.8926432

$`2.4`
[1] -1.9786356  0.2735958

$`2.5`
[1] 1.45663992 0.04630115

In [96]:
str(split(x,list(f1,f2),drop=TRUE))

List of 6
 $ 1.1: num [1:2] -1.226 0.183
 $ 1.2: num [1:2] 1.55 2.5
 $ 1.3: num -0.337
 $ 2.3: num 0.893
 $ 2.4: num [1:2] -1.979 0.274
 $ 2.5: num [1:2] 1.4566 0.0463


----

In [97]:
list(rep(1,4),rep(2,3),rep(3,2),rep(4,1))

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [98]:
mapply(rep,1:4,4:1) # Apply a Function to Multiple List or Vector Arguments

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

----

In [100]:
# function vectorization
noise<-function(n,mean,sd){
  rnorm(n,mean,sd)
}

In [101]:
noise(5,1,2)

[1] -1.727173 -1.157798  1.649579 -2.164184 -2.626874

In [104]:
noise(1:5,5:1,2)

[1] 4.2823094 3.7151600 0.5609886 2.2350063 1.5941845

In [105]:
mapply(noise,1:5,5:1,2)

[[1]]
[1] 4.973031

[[2]]
[1] 0.9543479 3.6370627

[[3]]
[1] 2.567910 4.049637 3.771944

[[4]]
[1] 1.160028 3.739054 2.894694 3.105935

[[5]]
[1] 0.6124152 0.4310907 0.1728687 1.1267893 2.9895745